config/routes.rb
Rails.application.routes.draw do
  get 'seats/reseat', to: 'seats#reseat'
  put 'seats/reset', to: 'seats#reset'
  resources :seats
  resources :users
  resources :records, only: [:index, :show, :new, :create]
  get '/home', to: 'home#index', as: 'home'

  root 'home#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
	belongs_to :user
	belongs_to :seat
end

app/models/seat.rb
class Seat < ActiveRecord::Base
	has_many :records
	has_many :users, :through => :records
	belongs_to :owner, class_name: "User"
	validates :owner_id, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :records
	has_many :seats, :through => :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@seats = Seat.all
		@users = User.all.order('total_hours DESC')
		segment_users
	end

	def segment_users
		Analytics.identify(user_id: "123", traits: { email: "pirate@gmail.com", name: "Kenny Chesney" })
	end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController


  def index
    @record = Record.all
  end

  def show
  end

	def new
		@record = Record.new
		@seats = Seat.where(owner_id: 0)
	end

	def create
		@record = Record.new(record_params)
		if @record.save
			update_total_hours(record_params[:user_id])
			redirect_to home_path
		else
			render 'new'
		end
	end

	private
	def record_params
		params.require(:record).permit(:seat_id, :user_id, :usage)
	end

	def update_total_hours(user_id)
		records = Record.where(user_id: user_id)
		user = User.find(user_id)
		total_usage = 0
		records.each do |record|
			total_usage += record.usage 
		end
		user.total_hours = total_usage
		user.save
	end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]
  before_action :check_owner_id, only: [:create]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    @seats = Seat.all
  end

  def reseat
    @seats = Seat.all
    @users = User.all.order('total_hours DESC')
    @new_seats = find_gainers
    @lose_seats = find_losers
    render 'reseat'
  end

  def reset
    @seats = Seat.all
    @users = User.all
    @seats.update_all(owner_id: 0)
    keepers = find_seat_keepers
    counter = 0
    @seats.each do |seat|
      seat.owner_id = keepers[counter].id
      counter += 1
      seat.save
    end
    @users.update_all(total_hours: 0)
    redirect_to home_path
  end

  def show
    @seat = Seat.find_by(id: params[:id])
    @owner = @seat.owner
    @record = Record.new
  end

  def new
    @seat = Seat.new
  end

  def edit
  end

  def create
    @seat = Seat.new(seat_params)
    if @seat.save
      redirect_to @seat
    else
      render 'new'
    end
  end

  def update
    if @seat.update(seat_params)
      redirect_to @seat
    else
      render 'edit'
    end
  end

  def destroy
    if @seat.destroy
      redirect_to seats_path
    end
  end


  private

  def set_seat
    @seat = Seat.find(params[:id])
  end

  def seat_params
    params.require(:seat).permit(:owner_id)
  end

  def record_not_found
    render plain: "404 Not Found", status: 404
  end

  def check_owner_id
    params = seat_params 
    if params[:owner_id] == "0"
      return "Communal Seat has been created"
    else
      if User.find_by(id: params[:owner_id]).nil?
        render plain: "Must assign seat to existing user"
      end
    end
  end

  def find_old_seats
    seats = Seat.all
    old_seats_id = []
    old = []
    seats.each do |seat|
      if seat.owner_id > 0
        old_seats_id << seat.owner_id
      end
    end
    old_seats_id.each do |id|
      old << User.find(id)
    end
    return old
  end

  def find_seat_keepers
    users = User.all.order('total_hours DESC')
    users_array = []
      users.each do |user|
       users_array << user
      end
    seat_count = Seat.all.count
    new_seat_users = []
    seat_count.times {new_seat_users << users_array.shift}
    return new_seat_users
  end

  def find_gainers
    new = find_seat_keepers
    old = find_old_seats
    new - old
  end

  def find_losers
    new = find_seat_keepers
    old = find_old_seats
    old - new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @records = Record.where(user_id: params[:id]).order('created_at ASC')
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :department)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hello</h1>

<table>

	<thead>
		<tr>
			<td>Total Seats:</td>
			<td><%= @seats.count %></td>
		</tr>
		<tr>
			<td>Total Users:</td>
			<td><%= @users.count %></td>
		</tr>
	</thead>
</table>
<%= render 'seats/ordered', layout: false %>

<table>
	<tbody>
		<tr>
			<th><%= link_to 'Edit Users', users_path %></th>
			<th><%= link_to 'Edit Seats', seats_path %></th>
			<th><%= link_to 'Reset Seating Arrangements', seats_reseat_path %></th>
			<th colspan="3"></th>
		</tr>
	</tbody>
</table>

<h2>This is the video</h2>

<iframe id="video_player" src="http://fast.wistia.net/embed/iframe/qv0hemx7ev" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="388"></iframe>
<script src="http://fast.wistia.net/assets/external/E-v1.js" async></script>


<script>
	window._wq = window._wq || [];
	_wq.push({ "video": function(video) {
	  video.bind("play", function() {
		  analytics.track('Played Video', {
				label: video.name(),
				category: 'Video',
				id: video.hashedId(),
				duration: video.duration()
	  	})
		});

		video.bind("pause", function() {
			if (video.time() < parseInt(video.duration())) {
	      analytics.track('Paused Video', {
	        label: video.name(),
	        category: 'Video',
	        id: video.hashedId(),
	        pausedAt: video.time()
	      });
    	};
		});

		video.bind("end", function() {
		  analytics.track('Finished Video', {
				label: video.name(),
				category: 'Video',
				id: video.hashedId(),
				duration: video.duration()
	  	})
  	});	

	}});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reseatly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
  analytics.load("RvuaqW5CVjPkb6TBzOsFlSdQ0W2y6SsA");
  analytics.page()
  }}();
	</script>
</head>
<body>

<%= link_to 'Home', home_path %>
<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<br>
<%= simple_form_for @record do |f| %>
	<%= f.input :user_id, :as => :hidden, :input_html => { :value => params[:user_id] } %>
  <%= f.input :seat_id, input_html: {value: params[:seat_id]} %><br/>
  <%= f.input :usage %><br/>
  <%= f.button :submit %>
<% end %>
<br>

app/views/records/new.html.erb
<h1>How long did you use your seat today?</h1>
<%= render 'form' %>
<%= link_to 'Back', records_path %>
<% if params[:seat_id].nil? %>
<p>List of Communal Standing Desks</p>
<ul>
<% @seats.each do |seat| %>
<li>Seat <%= seat.id %></li>
<% end %>
<% end %>
</ul>

app/views/seats/_form.html.erb
<%= simple_form_for @seat do |f| %>
  <%= f.input :owner_id %>
  <%= f.button :submit %>
<% end %>

app/views/seats/_ordered.html.erb
<table>
<tr>
<td> Employee ID </td>
<td> Name </td>
<td> Seat # </td>
<td> Total Hours </td>
</tr>
<tr>
<% @users.each do |user| %>
<td><%= user.id %></td>

<% if Seat.find_by(owner_id: user.id) %>
<td><a href="/users/<%=user.id %>?seat_id=<%=Seat.find_by(owner_id: user.id).id %>"><%= user.first_name %> <%= user.last_name %></a></td>
<td><%= Seat.find_by(owner_id: user.id).id %></td>

<% else %>
<td><a href="/users/<%= user.id %>"><%= user.first_name %> <%= user.last_name %></a></td>
<td>N/A</td>
<% end %>
<td><%= user.total_hours %></td>
</tr>
<% end %>

</table>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Seats</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @seats.each do |seat| %>
      <tr>
        <td>Seat Number</td>
        <td>Owner</td>
      </tr>
      <tr>
        <td><%= seat.id %></td>
        <% if seat.owner %>
        <td><%= seat.owner.first_name %></td>
        <% else %>
        <td>N/A</td>
        <% end %>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Remove', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<h1>New seat</h1>
<p>**Set to 0 if communal standing desk**</p>
<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/reseat.html.erb
<h2>Current Seat Arrangements</h2>
<%= render 'ordered', layout: false %>
<br>
<table>
<tr>
<td>Employees Who Gain A Standing Desk</td>
</tr>
<tr>
<% @new_seats.each do |seat| %>
<td><%= seat.first_name %></td>
<% end %>
</tr>
</table><br>

<table>
<tr>
<td>Employees Who Lose A Standing Desk</td>
</tr>
<tr>
<% @lose_seats.each do |seat| %>
<td><%= seat.first_name %></td>
<% end %>
</tr>
</table><br>

<%= button_to "Reset", seats_reset_path, :method => :put, data: {confirm: "Are you sure? This will reassign all seats and reset usage data to 0." } %>

app/views/seats/show.html.erb
<% if @owner %>
<h1>Seat <%= @seat.id %></h1>
<table>
	<tr>
		<td>First Name: </td>
		<td><%= @owner.first_name %></td>
	</tr>

	<tr>
		<td>Last Name: </td>
		<td><%= @owner.last_name %></td>
	</tr>
	<tr>
		<td>Department: </td>
		<td><%= @owner.department %></td>
	</tr>
</table>

<% else %> 
<p>This seat doesn't have an owner!</p>
<% end %>



<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.department %></td>
        <td><%= link_to 'History', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.department %>
</p>

<h3>History:</h3>
<table>
<tr>
<td>Record ID</td>
<td>Date</td>
<td>Hours</td>
</tr>
<% @records.each do |record| %>
<tr>
<td><%= record.id %> </td>
<td><%= record.created_at.strftime("%d %b. %Y") %></td>
<td><%= record.usage %></td>
</tr>
<% end %>
</table>
<br>
<%= link_to 'Add Record', new_record_path(user_id: params[:id], seat_id: params[:seat_id]) %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>